# Generated by Django 5.0.6 on 2024-09-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual', models.DecimalField(decimal_places=0, max_digits=10)),
                ('produtos', models.ManyToManyField(related_name='promocoes', to='produtos.produto')),
            ],
        ),
    ]
