# Generated by Django 5.0.6 on 2024-09-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='mercados',
            field=models.ManyToManyField(related_name='produtos', to='mercado.mercado'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tags',
            field=models.ManyToManyField(blank=True, to='produtos.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
