# Generated by Django 5.0.6 on 2024-09-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0002_alter_mercado_endereco_alter_mercado_nome'),
        ('produtos', '0002_alter_produto_categoria_alter_produto_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='mercado',
        ),
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='mercados',
            field=models.ManyToManyField(blank=True, related_name='produtos', to='mercado.mercado'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='produtos', to='produtos.tag'),
        ),
    ]
