# Generated by Django 5.0.6 on 2024-09-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercado',
            name='endereco',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mercado',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
